POST https://3000-emanuelgust-expressauth-9r32l4zhkks.ws-eu104.gitpod.io/users/login
Content-Type: application/json

{
    "username": "ingrid",
    "password": "secret"
}

###

GET https://3000-emanuelgust-expressauth-9r32l4zhkks.ws-eu104.gitpod.io/users/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTI3Mjg5MDcsImV4cCI6MTY5MjcyODkzN30.E9VZDpv0I63z2ilIKyWkBUtQZQEnVs-b-m-IMqsK9qk


###

POST https://3000-emanuelgust-expressauth-9r32l4zhkks.ws-eu104.gitpod.io/users/renewToken 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGU0ZmRmOGY1ODIzYmEyYThkZTZlZTciLCJpYXQiOjE2OTI3Mjg4MzQsImV4cCI6MTY5MjkzMDQzNH0.QH8RH7XzTof6j0_q5ougnAtr3TfYJyvGpFcDk1NaX7A